# This workflow will build a package using Java

name: Java Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
      
    - run: javac src/main/java/com/vroozi/HollowWorld.java
    - run: jar cf HollowWorld.jar src/main/java/com/vroozi/HollowWorld.class
    
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
        image: msharjeeltariq/github-action
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Upload JAR to GitHub Artifacts
      uses: actions/upload-artifact@v4.6.1
      with:
        name: HollowWorld.jar
        path: ${{ github.workspace }}/HollowWorld.jar
        if-no-files-found: error
      
    
